const express = require('express');
const bodyParser = require('body-parser');
const cors = require('cors');

const app = express();
const port = process.env.PORT || 4000; // Use the PORT provided by Render or default to 4000

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());

// Enable CORS
app.use(cors());
app.use(cors({
    origin: '*', // or specify allowed origins
    methods: ['GET', 'POST'],
    allowedHeaders: ['Content-Type']
  }));
  

const synonyms = {
   'happy': ['joyful', 'content', 'pleased'],
    'sad': ['unhappy', 'sorrowful', 'dejected'],
    'angry': ['furious', 'irate', 'livid'],
    'big': ['large', 'huge', 'massive'],
    'small': ['tiny', 'miniature', 'minute'],
    'smart': ['intelligent', 'clever', 'bright'],
    'stupid': ['foolish', 'unwise', 'idiotic'],
    'run': ['sprint', 'jog', 'dash'],
    'walk': ['stroll', 'saunter', 'amble'],
    'talk': ['speak', 'converse', 'chat'],
    'see': ['observe', 'view', 'notice'],
    'wield': ['exert', 'brandish', 'handle'],
    'youthful': ['vigorous', 'young', 'spry'],
    'zeal': ['fervor', 'enthusiasm', 'ardor'],
    'zenith': ['acme', 'peak', 'summit'],
    'look': ['glance', 'gaze', 'stare'],
    'make': ['create', 'produce', 'construct'],
    'eat': ['consume', 'devour', 'ingest'],
    'drink': ['sip', 'gulp', 'quaff'],
    'sleep': ['rest', 'slumber', 'nap'],
    'buy': ['purchase', 'acquire', 'obtain'],
    'rich': ['wealthy', 'affluent', 'opulent'],
    'poor': ['impoverished', 'destitute', 'needy'],
    'fast': ['quick', 'swift', 'rapid'],
    'slow': ['sluggish', 'lethargic', 'unhurried'],
    'old': ['ancient', 'elderly', 'venerable'],
    'young': ['youthful', 'juvenile', 'youngster'],
    'beautiful': ['gorgeous', 'lovely', 'attractive'],
    'ugly': ['unattractive', 'hideous', 'unsightly'],
    'happy': ['content', 'cheerful', 'delighted'],
    'sad': ['sorrowful', 'miserable', 'depressed'],
    'big': ['huge', 'massive', 'gigantic'],
    'small': ['little', 'tiny', 'minuscule'],
    'easy': ['simple', 'effortless', 'straightforward'],
    'difficult': ['hard', 'challenging', 'tough'],
    'hard': ['challenging', 'firm', 'difficult'],
    'soft': ['gentle', 'malleable', 'tender'],
    'strong': ['powerful', 'sturdy', 'robust'],
    'weak': ['feeble', 'frail', 'fragile'],
    'bright': ['radiant', 'luminous', 'brilliant'],
    'dark': ['dim', 'obscure', 'gloomy'],
    'clean': ['spotless', 'tidy', 'pristine'],
    'dirty': ['filthy', 'grimy', 'soiled'],
    'hot': ['scorching', 'boiling', 'sizzling'],
    'cold': ['chilly', 'frigid', 'frosty'],
    'warm': ['lukewarm', 'tepid', 'mild'],
    'cool': ['refreshing', 'chilly', 'brisk'],
    'new': ['fresh', 'novel', 'modern'],
    'ancient': ['antique', 'archaic', 'old'],
    'good': ['excellent', 'fine', 'superb'],
    'bad': ['terrible', 'awful', 'dreadful'],
    'loud': ['noisy', 'boisterous', 'deafening'],
    'quiet': ['silent', 'hushed', 'serene'],
    'tall': ['elevated', 'lofty', 'towering'],
    'short': ['brief', 'concise', 'stubby'],
    'long': ['lengthy', 'extended', 'protracted'],
    'wide': ['broad', 'expansive', 'vast'],
    'narrow': ['slender', 'confined', 'restricted'],
    'important': ['significant', 'crucial', 'vital'],
    'unimportant': ['trivial', 'insignificant', 'minor'],
    'expensive': ['costly', 'pricey', 'high-priced'],
    'cheap': ['inexpensive', 'affordable', 'economical'],
    'early': ['premature', 'initial', 'ahead'],
    'late': ['tardy', 'delayed', 'behind'],
    'true': ['genuine', 'authentic', 'real'],
    'false': ['incorrect', 'untrue', 'fake'],
    'right': ['correct', 'accurate', 'just'],
    'wrong': ['mistaken', 'erroneous', 'incorrect'],
    'brave': ['courageous', 'valiant', 'fearless'],
    'cowardly': ['fearful', 'timid', 'craven'],
    'clever': ['brilliant', 'ingenious', 'shrewd'],
    'dull': ['boring', 'uninteresting', 'bland'],
    'deep': ['profound', 'intense', 'vast'],
    'shallow': ['superficial', 'trivial', 'slight'],
    'fat': ['overweight', 'plump', 'chubby'],
    'thin': ['slender', 'lean', 'slim'],
    'full': ['complete', 'packed', 'filled'],
    'empty': ['vacant', 'bare', 'void'],
    'great': ['wonderful', 'fantastic', 'terrific'],
    'terrible': ['horrible', 'atrocious', 'abysmal'],
    'hard': ['firm', 'solid', 'sturdy'],
    'healthy': ['fit', 'well', 'robust'],
    'sick': ['ill', 'unwell', 'ailing'],
    'abate': ['moderate', 'diminish', 'lessen'],
    'adhere': ['comply', 'follow', 'obey'],
    'abolish': ['abrogate', 'annul', 'repeal'],
    'acumen': ['awareness', 'insight', 'shrewdness'],
    'abash': ['disconcert', 'embarrass', 'confuse'],
    'absolve': ['pardon', 'forgive', 'exonerate'],
    'abjure': ['forsake', 'renounce', 'disavow'],
    'abject': ['despicable', 'wretched', 'miserable'],
    'abound': ['flourish', 'thrive', 'prosper'],
    'abortive': ['vain', 'unsuccessful', 'futile'],
    'acrimony': ['harshness', 'bitterness', 'resentment'],
    'accord': ['agreement', 'harmony', 'consensus'],
    'adjunct': ['joined', 'attached', 'associated'],
    'adversity': ['misfortune', 'hardship', 'trouble'],
    'adherent': ['follower', 'supporter', 'disciple'],
    'adamant': ['stubborn', 'unyielding', 'inflexible'],
    'admonish': ['counsel', 'reprimand', 'warn'],
    'allay': ['pacify', 'calm', 'alleviate'],
    'alien': ['foreigner', 'outsider', 'stranger'],
    'ascend': ['climb', 'rise', 'mount'],
    'alleviate': ['abate', 'ease', 'relieve'],
    'allure': ['entice', 'tempt', 'attract'],
    'arraign': ['incriminate', 'accuse', 'charge'],
    'amplify': ['augment', 'intensify', 'increase'],
    'axiom': ['adage', 'proverb', 'maxim'],
    'audacity': ['boldness', 'bravery', 'courage'],
    'authentic': ['accurate', 'genuine', 'real'],
    'awkward': ['rude', 'clumsy', 'inept'],
    'barbarous': ['frustrate', 'savage', 'cruel'],
    'bleak': ['grim', 'dreary', 'hopeless'],
    'bewitching': ['alluring', 'enchanting', 'captivating'],
    'baroque': ['florid', 'ornate', 'elaborate'],
    'brittle': ['breakable', 'fragile', 'delicate'],
    'barrier': ['barricade', 'obstacle', 'blockade'],
    'baffle': ['astound', 'perplex', 'confound'],
    'bustle': ['commotion', 'hustle', 'activity'],
    'barren': ['desolate', 'infertile', 'unproductive'],
    'bawdy': ['erotic', 'lewd', 'risqué'],
    'bind': ['predicament', 'dilemma', 'quandary'],
    'batty': ['insane', 'crazy', 'mad'],
    'benevolent': ['benign', 'kind', 'charitable'],
    'befogged': ['becloud', 'confused', 'muddled'],
    'base': ['vulgar', 'low', 'mean'],
    'benign': ['favorable', 'kind', 'harmless'],
    'busy': ['active', 'occupied', 'engaged'],
    'bleak': ['austere', 'harsh', 'severe'],
    'bold': ['adventurous', 'daring', 'brave'],
    'boisterous': ['clamorous', 'rowdy', 'noisy'],
    'blunt': ['dull', 'unsharpened', 'direct'],
    'callous': ['obdurate', 'heartless', 'insensitive'],
    'capable': ['competent', 'able', 'skillful'],
    'calamity': ['adversity', 'disaster', 'catastrophe'],
    'calculating': ['canny', 'shrewd', 'scheming'],
    'calumny': ['defamation', 'slander', 'libel'],
    'captivity': ['imprisonment', 'confinement', 'detention'],
    'captivate': ['charm', 'enchant', 'fascinate'],
    'chaste': ['virtuous', 'pure', 'modest'],
    'cease': ['terminate', 'stop', 'halt'],
    'compassion': ['kindness', 'empathy', 'sympathy'],
    'chastise': ['punish', 'discipline', 'scold'],
    'concede': ['yield', 'admit', 'acknowledge'],
    'comprise': ['include', 'contain', 'encompass'],
    'consent': ['agree', 'approve', 'permit'],
    'concur': ['approve', 'agree', 'assent'],
    'consolidate': ['solidify', 'unify', 'strengthen'],
    'consequence': ['effect', 'result', 'outcome'],
    'contempt': ['scorn', 'disdain', 'disrespect'],
    'conspicuous': ['prominent', 'noticeable', 'obvious'],
    'contrary': ['dissimilar', 'opposite', 'contradictory'],
    'contradict': ['deny', 'oppose', 'refute'],
    'calm': ['harmonious', 'peaceful', 'tranquil'],
    'candid': ['blunt', 'honest', 'frank'],
    'camouflage': ['cloak', 'conceal', 'disguise'],
    'carnal': ['earthly', 'sensual', 'bodily'],
    'captivate': ['beguile', 'charm', 'enthrall'],
    'celebrated': ['acclaimed', 'famous', 'renowned'],
    'catholic': ['generic', 'universal', 'comprehensive'],
    'censure': ['rebuke', 'criticize', 'condemn'],
    'cement': ['plaster', 'bond', 'stick'],
    'clandestine': ['covert', 'secret', 'hidden'],
    'cheap': ['competitive', 'economical', 'inexpensive'],
    'coarse': ['bawdy', 'crude', 'rough'],
    'classic': ['simple', 'timeless', 'traditional'],
    'compact': ['bunched', 'dense', 'compressed'],
    'comic': ['clown', 'funny', 'humorous'],
    'conceit': ['egotism', 'arrogance', 'vanity'],
    'compress': ['abbreviate', 'condense', 'shrink'],
    'condemn': ['castigate', 'criticize', 'denounce'],
    'concord': ['agreement', 'harmony', 'unity'],
    'confident': ['bold', 'assured', 'self-reliant'],
    'creation': ['formation', 'invention', 'origination'],
    'courtesy': ['generosity', 'politeness', 'civility'],
    'cunning': ['acute', 'shrewd', 'crafty'],
    'decipher': ['interpret', 'decode', 'unravel'],
    'decay': ['collapse', 'rot', 'decompose'],
    'deceit': ['deception', 'fraud', 'trickery'],
    'defray': ['spend', 'pay', 'settle'],
    'defile': ['contaminate', 'pollute', 'sully'],
    'demolish': ['ruin', 'destroy', 'raze'],
    'deliberate': ['cautious', 'intentional', 'thoughtful'],
    'deride': ['mock', 'ridicule', 'taunt'],
    'deprive': ['despoil', 'rob', 'strip'],
    'dissuade': ['remonstrate', 'discourage', 'deter'],
    'disdain': ['detest', 'scorn', 'contempt'],
    'dense': ['opaque', 'thick', 'impenetrable'],
    'denounce': ['blame', 'condemn', 'criticize'],
    'despair': ['depression', 'hopelessness', 'misery'],
    'derogatory': ['sarcastic', 'disparaging', 'belittling'],
    'docile': ['pliable', 'obedient', 'compliant'],
    'destructive': ['catastrophic', 'devastating', 'ruinous'],
    'dwarf': ['diminutive', 'small', 'miniature'],
    'eclipse': ['diminution', 'obscuration', 'veil'],
    'eager': ['keen', 'enthusiastic', 'avid'],
    'ecstasy': ['delight', 'rapture', 'bliss'],
    'eccentric': ['strange', 'odd', 'quirky'],
    'encumbrance': ['hindrance', 'burden', 'obstacle'],
    'efface': ['destroy', 'erase', 'obliterate'],
    'eloquence': ['expression', 'fluency', 'oratory'],
    'enormous': ['colossal', 'immense', 'gigantic'],
    'elucidate': ['clarify', 'explain', 'illuminate'],
    'embellish': ['adorn', 'decorate', 'enhance'],
    'eliminate': ['remove', 'exterminate', 'eradicate'],
    'encourage': ['inspire', 'motivate', 'support'],
    'emulate': ['imitate', 'copy', 'replicate'],
    'eminent': ['distinguished', 'prominent', 'notable'],
    'enervate': ['exhaust', 'weaken', 'debilitate'],
    'equivocal': ['ambiguous', 'unclear', 'vague'],
    'exasperate': ['irritate', 'provoke', 'annoy'],
    'exceed': ['surpass', 'transcend', 'outdo'],
    'exhort': ['encourage', 'urge', 'implore'],
    'fabulous': ['legendary', 'mythical', 'imaginary'],
    'facetious': ['witty', 'humorous', 'joking'],
    'fallacy': ['delusion', 'misbelief', 'error'],
    'fertile': ['fruitful', 'productive', 'fecund'],
    'feeble': ['frail', 'weak', 'decrepit'],
    'fickle': ['capricious', 'changeable', 'inconstant'],
    'flamboyant': ['colorful', 'exuberant', 'showy'],
    'flawless': ['perfect', 'impeccable', 'unblemished'],
    'frugal': ['economical', 'thrifty', 'sparing'],
    'garish': ['flashy', 'gaudy', 'tawdry'],
    'genuine': ['authentic', 'real', 'sincere'],
    'garrulous': ['talkative', 'loquacious', 'verbose'],
    'gratuitous': ['unnecessary', 'superfluous', 'unjustified'],
    'gregarious': ['sociable', 'outgoing', 'friendly'],
    'hapless': ['unlucky', 'unfortunate', 'ill-fated'],
    'heinous': ['atrocious', 'monstrous', 'wicked'],
    'humble': ['modest', 'meek', 'unpretentious'],
    'hysterical': ['frantic', 'wild', 'overwrought'],
    'impartial': ['unbiased', 'neutral', 'fair'],
    'impecunious': ['penniless', 'poor', 'destitute'],
    'impetuous': ['rash', 'hasty', 'impulsive'],
    'incessant': ['continuous', 'unending', 'constant'],
    'inept': ['clumsy', 'incompetent', 'unskilled'],
    'innate': ['inherent', 'natural', 'inborn'],
    'insolent': ['impudent', 'rude', 'disrespectful'],
    'jovial': ['cheerful', 'merry', 'jolly'],
    'judicious': ['prudent', 'sensible', 'wise'],
    'keen': ['eager', 'sharp', 'intense'],
    'laconic': ['concise', 'terse', 'succinct'],
    'lethargic': ['sluggish', 'inactive', 'torpid'],
    'lucid': ['clear', 'intelligible', 'comprehensible'],
    'luminous': ['radiant', 'glowing', 'bright'],
    'magnanimous': ['generous', 'noble', 'big-hearted'],
    'malicious': ['spiteful', 'malevolent', 'hateful'],
    'melancholy': ['sorrowful', 'woeful', 'mournful'],
    'meticulous': ['thorough', 'detailed', 'precise'],
    'munificent': ['generous', 'lavish', 'bountiful'],
    'naive': ['innocent', 'unsophisticated', 'gullible'],
    'nefarious': ['wicked', 'evil', 'villainous'],
    'negligent': ['careless', 'remiss', 'irresponsible'],
    'novice': ['beginner', 'learner', 'neophyte'],
    'obsolete': ['outdated', 'antiquated', 'outmoded'],
    'ominous': ['threatening', 'foreboding', 'menacing'],
    'opulent': ['luxurious', 'wealthy', 'lavish'],
    'ornate': ['elaborate', 'decorative', 'flamboyant'],
    'paltry': ['insignificant', 'trivial', 'meager'],
    'paragon': ['exemplar', 'model', 'ideal'],
    'peculiar': ['strange', 'odd', 'unusual'],
    'perplex': ['confuse', 'puzzle', 'baffle'],
    'placid': ['calm', 'tranquil', 'serene'],
    'plentiful': ['abundant', 'bountiful', 'copious'],
    'poignant': ['moving', 'touching', 'emotional'],
    'precocious': ['advanced', 'mature', 'gifted'],
    'preposterous': ['ridiculous', 'absurd', 'ludicrous'],
    'prodigious': ['enormous', 'huge', 'immense'],
    'proficient': ['skilled', 'competent', 'adept'],
    'quaint': ['picturesque', 'charming', 'antique'],
    'quell': ['suppress', 'subdue', 'extinguish'],
    'querulous': ['complaining', 'whining', 'fretful'],
    'quixotic': ['idealistic', 'impractical', 'romantic'],
    'radiant': ['glowing', 'brilliant', 'shining'],
    'rapacious': ['greedy', 'grasping', 'avaricious'],
    'ravenous': ['hungry', 'voracious', 'insatiable'],
    'recalcitrant': ['rebellious', 'defiant', 'obstinate'],
    'reclusive': ['solitary', 'isolated', 'secluded'],
    'refute': ['disprove', 'debunk', 'rebut'],
    'remiss': ['negligent', 'careless', 'irresponsible'],
    'resilient': ['tough', 'hardy', 'flexible'],
    'resolute': ['determined', 'steadfast', 'unwavering'],
    'reticent': ['reserved', 'withdrawn', 'introverted'],
    'robust': ['strong', 'healthy', 'vigorous'],
    'rudimentary': ['basic', 'elementary', 'fundamental'],
    'salient': ['notable', 'important', 'significant'],
    'sanguine': ['optimistic', 'cheerful', 'positive'],
    'sedentary': ['inactive', 'stationary', 'seated'],
    'serendipity': ['chance', 'fortune', 'luck'],
    'sinister': ['menacing', 'threatening', 'evil'],
    'soporific': ['sleep-inducing', 'drowsy', 'sedative'],
    'staunch': ['loyal', 'faithful', 'steadfast'],
    'stringent': ['strict', 'rigorous', 'severe'],
    'subtle': ['delicate', 'faint', 'understated'],
    'superfluous': ['unnecessary', 'redundant', 'excessive'],
    'surreptitious': ['secret', 'stealthy', 'clandestine'],
    'taciturn': ['silent', 'reserved', 'reticent'],
    'tedious': ['boring', 'dull', 'monotonous'],
    'tenacious': ['persistent', 'determined', 'dogged'],
    'thrifty': ['economical', 'frugal', 'sparing'],
    'truculent': ['hostile', 'belligerent', 'aggressive'],
    'ubiquitous': ['omnipresent', 'everywhere', 'universal'],
    'unctuous': ['sycophantic', 'flattering', 'oily'],
    'venerable': ['respected', 'esteemed', 'revered'],
    'verbose': ['wordy', 'long-winded', 'prolix'],
    'vex': ['annoy', 'irritate', 'provoke'],
    'vigilant': ['watchful', 'alert', 'attentive'],
    'vitiate': ['spoil', 'mar', 'corrupt'],
    'vivacious': ['lively', 'animated', 'spirited'],
    'volatile': ['unstable', 'unpredictable', 'explosive'],
    'wanton': ['reckless', 'heedless', 'malicious'],
    'wary': ['cautious', 'careful', 'alert'],
    'wistful': ['nostalgic', 'yearning', 'longing'],
    'zealous': ['enthusiastic', 'fervent', 'ardent'],
    'heavy': ['weighty', 'hefty', 'burdensome'],
    'light': ['airy', 'lightweight', 'flimsy'],
    'high': ['elevated', 'lofty', 'tall'],
    'low': ['depressed', 'shallow', 'short'],
    'large': ['gigantic', 'immense', 'massive'],
    'lazy': ['sluggish', 'idle', 'lethargic'],
    'active': ['energetic', 'lively', 'dynamic'],
    'pretty': ['attractive', 'lovely', 'beautiful'],
    'quick': ['prompt', 'speedy', 'swift'],
    'safe': ['secure', 'protected', 'harmless'],
    'dangerous': ['hazardous', 'perilous', 'risky'],
    'simple': ['plain', 'straightforward', 'uncomplicated'],
    'complex': ['complicated', 'intricate', 'elaborate'],
    'tall': ['lofty', 'elevated', 'towering'],
    'thin': ['lean', 'slender', 'skinny'],
    'wet': ['damp', 'soaked', 'soggy'],
    'dry': ['arid', 'parched', 'dehydrated'],
    'wide': ['broad', 'expansive', 'spacious'],
    'narrow': ['slender', 'tight', 'cramped'],
    'young': ['youthful', 'juvenile', 'adolescent'],
    'old': ['elderly', 'aged', 'senior'],
    'happy': ['joyful', 'cheerful', 'merry'],
    'sad': ['unhappy', 'sorrowful', 'mournful'],
    'angry': ['furious', 'irate', 'enraged'],
    "many": ["numerous", "several", "a lot of"],
  "people": ["individuals", "persons", "citizens"],
  "believe": ["think", "consider", "hold"],
  "that": ["which", "whereas", "while"],
  "technology": ["innovation", "electronics", "engineering"],
  "has": ["possesses", "holds", "contains"],
  "greatly": ["significantly", "considerably", "substantially"],
  "improved": ["enhanced", "bettered", "boosted"],
  "our": ["the", "one's", "your"],
  "lives": ["existence", "lifestyle", "being"],
  "making": ["creating", "producing", "forming"],
  "tasks": ["jobs", "duties", "assignments"],
  "easier": ["simpler", "more convenient", "less complicated"],
  "and": ["as well as", "in addition to", "plus"],
  "communication": ["interaction", "connection", "conversation"],
  "more": ["increased", "greater", "additional"],
  "convenient": ["handy", "accessible", "user-friendly"],
  "however": ["nevertheless", "yet", "though"],
  "others": ["alternatives", "different ones", "opposites"],
  "argue": ["debate", "contend", "discuss"],
  "also": ["additionally", "furthermore", "likewise"],
  "led": ["guided", "directed", "conducted"],
  "to": ["resulted in", "caused", "brought about"],
  "negative": ["adverse", "unfavorable", "detrimental"],
  "consequences": ["results", "outcomes", "effects"],
  "such": ["like", "similar", "comparable"],
  "as": ["like", "for example", "such as"],
  "social": ["societal", "community", "public"],
  "isolation": ["separation", "solitude", "loneliness"],
  "decreased": ["reduced", "lowered", "diminished"],
  "physical": ["bodily", "corporeal", "material"],
  "activity": ["exercise", "movement", "workout"],
  "it": ["this", "that", "the"],
  "important": ["crucial", "significant", "vital"],
  "strike": ["hit", "beat", "pound"],
  "a": ["an", "one", "each"],
  "balance": ["equilibrium", "stability", "harmony"],
  "between": ["among", "amid", "within"],
  "embracing": ["adopting", "accepting", "welcoming"],
  "advancements": ["developments", "progress", "improvements"],
  "maintaining": ["preserving", "sustaining", "upholding"],
  "healthy": ["well", "fit", "sound"],
  "lifestyles": ["ways of life", "living styles", "habits"],
  "streaming": ["streaming", "broadcasting", "transmitting"],
"services": ["services", "facilities", "amenities"],
"online": ["online", "on the internet", "over the web"],
"gaming": ["gaming", "playing", "gambling"],
"platforms": ["platforms", "platform", "stage"],
"and": ["and", "as well as", "along with"],
"immersive": ["immersive", "engrossing", "absorbing"],
"virtual": ["virtual", "computer-generated", "simulated"],
"experiences": ["experiences", "encounters", "events"],
"redefining": ["redefining", "reshaping", "transforming"],
"how": ["how", "in what way", "the manner in which"],
"people": ["people", "individuals", "humans"],
"consume": ["consume", "use", "utilize"],
"media": ["media", "medium", "means"],
"and": ["and", "as well as", "along with"],
"engage": ["engage", "participate", "get involved"],
"with": ["with", "along with", "together with"],
"entertainment": ["entertainment", "amusement", "recreation"],
"content": ["content", "material", "information"],
"However": ["However", "Nevertheless", "Nonetheless"],
"alongside": ["alongside", "beside", "next to"],
"the": ["the", "the", "the"],
"benefits": ["benefits", "advantages", "positives"],
"of": ["of", "in", "at"],
"technological": ["technological", "technical", "scientific"],
"progress": ["progress", "advancement", "development"],
"come": ["come", "arrive", "occur"],
"challenges": ["challenges", "difficulties", "obstacles"],
"and": ["and", "as well as", "along with"],
"concerns": ["concerns", "worries", "issues"],
"The": ["The", "This", "That"],
"widespread": ["widespread", "extensive", "ubiquitous"],
"use": ["use", "usage", "utilization"],
"of": ["of", "in", "at"],
"smartphones": ["smartphones", "mobile phones", "cell phones"],
"and": ["and", "as well as", "along with"],
"social": ["social", "societal", "communal"],
"media": ["media", "medium", "means"],
"has": ["has", "possesses", "holds"],
"raised": ["raised", "lifted", "elevated"],
"concerns": ["concerns", "worries", "issues"],
"about": ["about", "concerning", "regarding"],
"privacy": ["privacy", "confidentiality", "secrecy"],
"digital": ["digital", "electronic", "computerized"],
"addiction": ["addiction", "dependency", "obsession"],
"and": ["and", "as well as", "along with"],
"the": ["the", "the", "the"],
"impact": ["impact", "effect", "influence"],
"of": ["of", "in", "at"],
"excessive": ["excessive", "extreme", "unreasonable"],
"screen": ["screen", "display", "monitor"],
"time": ["time", "period", "duration"],
"on": ["on", "upon", "onto"],
"mental": ["mental", "psychological", "emotional"],
"health": ["health", "well-being", "mental well-being"],
"Cybersecurity": ["Cybersecurity", "Information security", "Data protection"],
"threats": ["threats", "risks", "dangers"],
"data": ["data", "information", "facts"],
"breaches": ["breaches", "violations", "intrusions"],
"and": ["and", "as well as", "along with"],
"online": ["online", "internet", "web-based"],
"scams": ["scams", "frauds", "deceptions"],
"pose": ["pose", "present", "cause"],
"risks": ["risks", "dangers", "threats"],
"to": ["to", "towards", "into"],
"individuals": ["individuals", "people", "persons"],
"and": ["and", "as well as", "along with"],
"organizations": ["organizations", "companies", "institutions"],
"highlighting": ["highlighting", "emphasizing", "underscoring"],
"the": ["the", "the", "the"],
"need": ["need", "requirement", "necessity"],
"for": ["for", "in favor of", "in support of"],
"robust": ["robust", "strong", "sturdy"],
"cybersecurity": ["cybersecurity", "information security", "data protection"],
"measures": ["measures", "steps", "actions"],
"and": ["and", "as well as", "along with"],
"digital": ["digital", "electronic", "computerized"],
"literacy": ["literacy", "knowledge", "education"],
"education": ["education", "learning", "instruction"],
"Moreover": ["Moreover", "Furthermore", "Additionally"],
"the": ["the", "the", "the"],
"rise": ["rise", "increase", "escalation"],
"of": ["of", "in", "at"],
"automation": ["automation", "mechanization", "robotization"],
"and": ["and", "as well as", "along with"],
"artificial": ["artificial", "synthetic", "man-made"],
"intelligence": ["intelligence", "AI", "cognitive abilities"],
"has": ["has", "possesses", "holds"],
"sparked": ["sparked", "ignited", "triggered"],
"debates": ["debates", "discussions", "arguments"],
"about": ["about", "concerning", "regarding"],
"the": ["the", "the", "the"],
"future": ["future", "tomorrow", "the coming years"],
"of": ["of", "in", "at"],
"work": ["work", "employment", "jobs"],
"job": ["job", "employment", "occupation"],
"displacement": ["displacement", "removal", "exclusion"],
"and": ["and", "as well as", "along with"],
"income": ["income", "earnings", "revenue"],
"consult": ["consult", "seek advice", "talk to"],
"with": ["with", "along with", "together with"],
"healthcare": ["healthcare", "medical care", "medicine"],
"providers": ["providers", "suppliers", "vendors"],
"remotely": ["remotely", "from a distance", "at a distance"],
"breaking": ["breaking", "shattering", "smashing"],
"down": ["down", "lowering", "reducing"],
"geographical": ["geographical", "spatial", "physical"],
"barriers": ["barriers", "obstacles", "hurdles"],
"and": ["and", "as well as", "along with"],
"improving": ["improving", "enhancing", "boosting"],
"access": ["access", "entry", "availability"],
"to": ["to", "towards", "into"],
"medical": ["medical", "health", "clinical"],
"services": ["services", "facilities", "assistance"],
"Moreover": ["Moreover", "Furthermore", "Additionally"],
"wearable": ["wearable", "portable", "mobile"],
"devices": ["devices", "gadgets", "tools"],
"and": ["and", "as well as", "along with"],
"health-monitoring": ["health-monitoring", "health-tracking", "wellness-monitoring"],
"apps": ["apps", "applications", "software"],
"empower": ["empower", "enable", "strengthen"],
"individuals": ["individuals", "people", "persons"],
"to": ["to", "towards", "into"],
"track": ["track", "monitor", "follow"],
"their": ["their", "their own", "their very own"],
"fitness": ["fitness", "physical condition", "health"],
"levels": ["levels", "degrees", "amounts"],
"monitor": ["monitor", "watch", "observe"],
"vital": ["vital", "essential", "crucial"],
"signs": ["signs", "indicators", "symptoms"],
"and": ["and", "as well as", "along with"],
"take": ["take", "undertake", "engage in"],
"proactive": ["proactive", "preemptive", "forward-looking"],
"steps": ["steps", "measures", "actions"],
"towards": ["towards", "in the direction of", "heading for"],
"better": ["better", "improved", "enhanced"],
"health": ["health", "wellness", "well-being"],
"In": ["In", "Inside", "Within"],
"education": ["education", "learning", "instruction"],
"technology": ["technology", "technological advancements", "innovation"],
"has": ["has", "possesses", "holds"],
"transformed": ["transformed", "changed", "altered"],
"traditional": ["traditional", "conventional", "standard"],
"classrooms": ["classrooms", "lecture halls", "educational settings"],
"into": ["into", "to", "within"],
"dynamic": ["dynamic", "energetic", "active"],
"learning": ["learning", "education", "knowledge acquisition"],
"environments": ["environments", "settings", "surroundings"],
"where": ["where", "in which", "wherein"],
"students": ["students", "pupils", "learners"],
"can": ["can", "could", "may"],
"access": ["access", "entry", "availability"],
"a": ["a", "an", "one"],
"wealth": ["wealth", "abundance", "riches"],
"of": ["of", "in", "at"],
"educational": ["educational", "learning", "instructional"],
"resources": ["resources", "materials", "assets"],
"online": ["online", "on the internet", "over the web"],
"participate": ["participate", "join in", "take part"],
"in": ["in", "within", "inside"],
"interactive": ["interactive", "participatory", "collaborative"],
"lessons": ["lessons", "classes", "lectures"],
"and": ["and", "as well as", "along with"],
"collaborate": ["collaborate", "work together", "cooperate"],
"with": ["with", "along with", "together with"],
"peers": ["peers", "colleagues", "fellow students"],
"globally": ["globally", "worldwide", "internationally"],
"Digital": ["Digital", "Electronic", "Computerized"],
"textbooks": ["textbooks", "e-books", "electronic books"],
"e-learning": ["e-learning", "online learning", "digital learning"],
"platforms": ["platforms", "platform", "stage"],
"and": ["and", "as well as", "along with"],
"virtual": ["virtual", "computer-generated", "simulated"],
"reality": ["reality", "real life", "actual existence"],
"simulations": ["simulations", "models", "replications"],
"offer": ["offer", "provide", "present"],
"engaging": ["engaging", "captivating", "interesting"],
"alternatives": ["alternatives", "options", "choices"],
"to": ["to", "towards", "into"],
"traditional": ["traditional", "conventional", "standard"],
"teaching": ["teaching", "instruction", "education"],
"methods": ["methods", "approaches", "techniques"],
"catering": ["catering", "providing for", "serving"],
"to": ["to", "towards", "into"],
"diverse": ["diverse", "varied", "different"],
"learning": ["learning", "education", "knowledge acquisition"],
"styles": ["styles", "approaches", "methods"],
"and": ["and", "as well as", "along with"],
"preferences": ["preferences", "choices", "likings"],
"The": ["The", "This", "That"],
"entertainment": ["entertainment", "amusement", "recreation"],
"industry": ["industry", "business", "sector"],
"has": ["has", "possesses", "holds"],
"also": ["also", "additionally", "furthermore"],
"undergone": ["undergone", "experienced", "been through"],
"a": ["a", "an", "one"],
"digital": ["digital", "electronic", "computerized"],
"revolution": ["revolution", "transformation", "overhaul"],
"The": ["The", "This", "That"],
"rapid": ["rapid", "quick", "fast"],
"advancement": ["advancement", "progress", "development"],
"of": ["of", "in", "at"],
"technology": ["technology", "technological advancements", "innovation"],
"in": ["in", "within", "inside"],
"the": ["the", "the", "the"],
"modern": ["modern", "contemporary", "current"],
"era": ["era", "age", "epoch"],
"has": ["has", "possesses", "holds"],
"revolutionized": ["revolutionized", "transformed", "changed"],
"nearly": ["nearly", "almost", "virtually"],
"every": ["every", "each", "all"],
"aspect": ["aspect", "facet", "dimension"],
"of": ["of", "in", "at"],
"human": ["human", "mankind's", "people's"],
"life": ["life", "existence", "living"],
"From": ["From", "Starting from", "Beginning with"],
"communication": ["communication", "contact", "interaction"],
"and": ["and", "as well as", "along with"],
"transportation": ["transportation", "travel", "movement"],
"to": ["to", "towards", "into"],
"healthcare": ["healthcare", "medical care", "medicine"],
"and": ["and", "as well as", "along with"],
"entertainment": ["entertainment", "amusement", "recreation"],
"technology": ["technology", "technological advancements", "innovation"],
"plays": ["plays", "performs", "acts"],
"a": ["a", "an", "one"],
"pivotal": ["pivotal", "central", "crucial"],
"role": ["role", "function", "part"],
"in": ["in", "within", "inside"],
"shaping": ["shaping", "molding", "forming"],
"our": ["our", "our own", "our very own"],
"daily": ["daily", "everyday", "day-to-day"],
"experiences": ["experiences", "encounters", "events"],
"The": ["The", "This", "That"],
"advent": ["advent", "arrival", "coming"],
"of": ["of", "in", "at"],
"the": ["the", "the", "the"],
"internet": ["internet", "web", "online world"],
"smartphones": ["smartphones", "mobile phones", "cell phones"],
"and": ["and", "as well as", "along with"],
"social": ["social", "socializing", "societal"],
"media": ["media", "medium", "means"],
"platforms": ["platforms", "platform", "stage"],
"has": ["has", "possesses", "holds"],
"interconnected": ["interconnected", "connected", "linked"],
"people": ["people", "individuals", "humans"],
"across": ["across", "throughout", "all over"],
"the": ["the", "the", "the"],
"globe": ["globe", "world", "planet"],
"facilitating": ["facilitating", "making easier", "simplifying"],
"instant": ["instant", "immediate", "quick"],
"communication": ["communication", "contact", "interaction"],
"and": ["and", "as well as", "along with"],
"information": ["information", "data", "facts"],
"sharing": ["sharing", "exchange", "transferring"],
"Tasks": ["Tasks", "Jobs", "Assignments"],
"that": ["that", "which", "those"],
"once": ["once", "previously", "formerly"],
"required": ["required", "needed", "necessitated"],
"extensive": ["extensive", "widespread", "wide-ranging"],
"manual": ["manual", "physical", "hand-operated"],
"labor": ["labor", "work", "effort"],
"or": ["or", "otherwise", "alternatively"],
"time-consuming": ["time-consuming", "slow", "long-winded"],
"processes": ["processes", "procedures", "methods"],
"can": ["can", "could", "may"],
"now": ["now", "at present", "currently"],
"be": ["be", "become", "turn into"],
"accomplished": ["accomplished", "achieved", "completed"],
"with": ["with", "along with", "together with"],
"the": ["the", "the", "the"],
"click": ["click", "press", "tap"],
"of": ["of", "in", "at"],
"a": ["a", "an", "one"],
"button": ["button", "switch", "control"],
"or": ["or", "otherwise", "alternatively"],
"the": ["the", "the", "the"],
"swipe": ["swipe", "brush", "sweep"],
"of": ["of", "in", "at"],
"a": ["a", "an", "one"],
"screen": ["screen", "display", "monitor"],
"In": ["In", "Inside", "Within"],
"the": ["the", "the", "the"],
"field": ["field", "area", "domain"],
"of": ["of", "in", "at"],
"healthcare": ["healthcare", "medical care", "medicine"],
"technological": ["technological", "technical", "scientific"],
"innovations": ["innovations", "developments", "breakthroughs"],
"have": ["have", "possess", "hold"],
"led": ["led", "guided", "directed"],
"to": ["to", "towards", "into"],
"breakthroughs": ["breakthroughs", "advancements", "discoveries"],
"in": ["in", "within", "inside"],
"medical": ["medical", "health", "clinical"],
"treatments": ["treatments", "therapies", "remedies"],
"diagnostics": ["diagnostics", "tests", "screenings"],
"and": ["and", "as well as", "along with"],
"patient": ["patient", "client", "customer"],
"care": ["care", "attention", "treatment"],
"Telemedicine": ["Telemedicine", "Remote medicine", "Online healthcare"],
"allows": ["allows", "permits", "enables"],
"patients": ["patients", "clients", "individuals"],
"performing": ["performing", "executing", "carrying out"],
"tasks": ["tasks", "jobs", "assignments"],
"traditionally": ["traditionally", "typically", "commonly"],
"done": ["done", "performed", "executed"],
"by": ["by", "through", "via"],
"humans": ["humans", "people", "individuals"],
"there": ["there", "here", "in that place"],
"is": ["is", "exists", "occurs"],
"a": ["a", "an", "one"],
"growing": ["growing", "expanding", "increasing"],
"need": ["need", "requirement", "demand"],
"to": ["to", "towards", "into"],
"adapt": ["adapt", "adjust", "modify"],
"to": ["to", "towards", "into"],
"the": ["the", "the", "the"],
"changing": ["changing", "evolving", "shifting"],
"nature": ["nature", "character", "essence"],
"of": ["of", "in", "within"],
"work": ["work", "employment", "jobs"],
"and": ["and", "as well as", "along with"],
"ensure": ["ensure", "guarantee", "assure"],
"that": ["that", "which", "those"],
"technological": ["technological", "technical", "scientific"],
"advancements": ["advancements", "progress", "developments"],
"benefit": ["benefit", "advantage", "gain"],
"society": ["society", "community", "population"],
"as": ["as", "since", "because"],
"a": ["a", "an", "one"],
"whole": ["whole", "entire", "complete"],
"Despite": ["Despite", "In spite of", "Regardless of"],
"these": ["these", "those", "such"],
"challenges": ["challenges", "obstacles", "difficulties"],
"the": ["the", "the", "the"],
"potential": ["potential", "possibility", "likelihood"],
"of": ["of", "in", "within"],
"technology": ["technology", "technological advancements", "innovation"],
"to": ["to", "towards", "into"],
"drive": ["drive", "propel", "push"],
"positive": ["positive", "beneficial", "constructive"],
"change": ["change", "transformation", "modification"],
"and": ["and", "as well as", "along with"],
"improve": ["improve", "enhance", "boost"],
"lives": ["lives", "existence", "living"],
"remains": ["remains", "stays", "continues"],
"immense": ["immense", "huge", "enormous"],
"By": ["By", "Through", "Using"],
"harnessing": ["harnessing", "utilizing", "employing"],
"the": ["the", "the", "the"],
"power": ["power", "strength", "force"],
"of": ["of", "in", "within"],
"innovation": ["innovation", "creativity", "invention"],
"collaboration": ["collaboration", "cooperation", "partnership"],
"and": ["and", "as well as", "along with"],
"responsible": ["responsible", "accountable", "reliable"],
"use": ["use", "utilization", "application"],
"of": ["of", "in", "within"],
"technology": ["technology", "technological advancements", "innovation"],
"we": ["we", "us", "ourselves"],
"can": ["can", "could", "may"],
"create": ["create", "generate", "produce"],
"a": ["a", "an", "one"],
"future": ["future", "prospects", "potential"],
"where": ["where", "in which", "wherein"],
"technological": ["technological", "technical", "scientific"],
"progress": ["progress", "advancement", "development"],
"enhances": ["enhances", "improves", "boosts"],
"human": ["human", "mankind's", "people's"],
"well-being": ["well-being", "health", "welfare"],
"fosters": ["fosters", "promotes", "encourages"],
"inclusivity": ["inclusivity", "inclusion", "diversity"],
"and": ["and", "as well as", "along with"],
"creates": ["creates", "generates", "produces"],
"opportunities": ["opportunities", "chances", "possibilities"],
"for": ["for", "of", "to"],
"platforms": ["platforms", "sites", "systems"],
"and": ["and", "as well as", "along with"],
"immersive": ["immersive", "engaging", "absorbing"],
"virtual": ["virtual", "computer-generated", "simulated"],
"experiences": ["experiences", "encounters", "events"],
"redefining": ["redefining", "reshaping", "transforming"],
"how": ["how", "in what way", "the way in which"],
"people": ["people", "individuals", "persons"],
"consume": ["consume", "use", "utilize"],
"media": ["media", "communications", "content"],
"and": ["and", "as well as", "along with"],
"engage": ["engage", "participate", "involve"],
"with": ["with", "using", "by means of"],
"entertainment": ["entertainment", "amusement", "diversion"],
"content": ["content", "material", "information"],
"However": ["However", "Nevertheless", "Nonetheless"],
"alongside": ["alongside", "along with", "beside"],
"the": ["the", "the", "the"],
"benefits": ["benefits", "advantages", "pros"],
"of": ["of", "in", "within"],
"technological": ["technological", "technical", "scientific"],
"progress": ["progress", "advancement", "development"],
"come": ["come", "arrive", "appear"],
"challenges": ["challenges", "difficulties", "obstacles"],
"and": ["and", "as well as", "along with"],
"concerns": ["concerns", "worries", "issues"],
"The": ["The", "That", "This"],
"widespread": ["widespread", "prevalent", "common"],
"use": ["use", "utilization", "application"],
"of": ["of", "in", "within"],
"smartphones": ["smartphones", "mobile phones", "cellphones"],
"and": ["and", "as well as", "along with"],
"social": ["social", "societal", "community"],
"media": ["media", "communications", "networks"],
"has": ["has", "possesses", "holds"],
"raised": ["raised", "lifted", "elevated"],
"concerns": ["concerns", "worries", "issues"],
"about": ["about", "concerning", "regarding"],
"privacy": ["privacy", "confidentiality", "secrecy"],
"digital": ["digital", "electronic", "online"],
"addiction": ["addiction", "dependency", "obsession"],
"and": ["and", "as well as", "along with"],
"the": ["the", "the", "the"],
"impact": ["impact", "effect", "influence"],
"of": ["of", "in", "on"],
"excessive": ["excessive", "extreme", "unreasonable"],
"screen": ["screen", "display", "monitor"],
"time": ["time", "period", "duration"],
"on": ["on", "upon", "onto"],
"mental": ["mental", "psychological", "emotional"],
"health": ["health", "well-being", "mental well-being"],
"Cybersecurity": ["Cybersecurity", "Internet security", "Information security"],
"threats": ["threats", "dangers", "risks"],
"data": ["data", "information", "facts"],
"breaches": ["breaches", "violations", "infringements"],
"and": ["and", "as well as", "along with"],
"online": ["online", "internet", "web-based"],
"scams": ["scams", "frauds", "deceptions"],
"pose": ["pose", "present", "create"],
"risks": ["risks", "dangers", "threats"],
"to": ["to", "towards", "into"],
"individuals": ["individuals", "people", "persons"],
"and": ["and", "as well as", "along with"],
"organizations": ["organizations", "companies", "groups"],
"highlighting": ["highlighting", "emphasizing", "underscoring"],
"the": ["the", "the", "the"],
"need": ["need", "requirement", "necessity"],
"for": ["for", "of", "to"],
"robust": ["robust", "strong", "resilient"],
"cybersecurity": ["cybersecurity", "internet security", "online security"],
"measures": ["measures", "steps", "actions"],
"and": ["and", "as well as", "along with"],
"digital": ["digital", "electronic", "computerized"],
"literacy": ["literacy", "education", "knowledge"],
"Moreover": ["Moreover", "Furthermore", "Additionally"],
"the": ["the", "the", "the"],
"rise": ["rise", "increase", "growth"],
"of": ["of", "in", "within"],
"automation": ["automation", "mechanization", "robotization"],
"and": ["and", "as well as", "along with"],
"artificial": ["artificial", "synthetic", "man-made"],
"intelligence": ["intelligence", "AI", "artificial intelligence"],
"has": ["has", "possesses", "holds"],
"sparked": ["sparked", "ignited", "triggered"],
"debates": ["debates", "discussions", "arguments"],
"about": ["about", "concerning", "regarding"],
"the": ["the", "the", "the"],
"future": ["future", "prospects", "potential"],
"of": ["of", "in", "within"],
"work": ["work", "employment", "jobs"],
"job": ["job", "employment", "occupation"],
"displacement": ["displacement", "relocation", "moving"],
"and": ["and", "as well as", "along with"],
"income": ["income", "earnings", "revenue"],
"inequality": ["inequality", "disparity", "unfairness"],
"As": ["As", "Since", "Because"],
"machines": ["machines", "devices", "equipment"],
"become": ["become", "get", "grow"],
"increasingly": ["increasingly", "progressively", "gradually"],
"capable": ["capable", "able", "competent"],
"remotely": ["remotely", "from a distance", "at a distance"],
"breaking": ["breaking", "shattering", "smashing"],
"down": ["down", "breaking down", "disassembling"],
"geographical": ["geographical", "geographic", "spatial"],
"barriers": ["barriers", "obstacles", "hindrances"],
"and": ["and", "as well as", "along with"],
"improving": ["improving", "enhancing", "upgrading"],
"access": ["access", "entry", "admission"],
"to": ["to", "towards", "into"],
"medical": ["medical", "medicinal", "health"],
"services": ["services", "facilities", "amenities"],
"Moreover": ["Moreover", "Furthermore", "Additionally"],
"wearable": ["wearable", "portable", "mobile"],
"devices": ["devices", "gadgets", "instruments"],
"and": ["and", "as well as", "along with"],
"health-monitoring": ["health-monitoring", "health-tracking", "wellness-tracking"],
"apps": ["apps", "applications", "software"],
"empower": ["empower", "enable", "authorize"],
"individuals": ["individuals", "people", "persons"],
"to": ["to", "towards", "into"],
"track": ["track", "monitor", "follow"],
"their": ["their", "the", "one's"],
"fitness": ["fitness", "physical fitness", "health"],
"levels": ["levels", "amounts", "quantities"],
"monitor": ["monitor", "observe", "watch"],
"vital": ["vital", "essential", "crucial"],
"signs": ["signs", "indicators", "symptoms"],
"and": ["and", "as well as", "along with"],
"take": ["take", "adopt", "undergo"],
"proactive": ["proactive", "preventive", "precautionary"],
"steps": ["steps", "measures", "actions"],
"towards": ["towards", "in the direction of", "heading to"],
"better": ["better", "improved", "enhanced"],
"health": ["health", "wellness", "fitness"],
"In": ["In", "Within", "Inside"],
"education": ["education", "learning", "instruction"],
"technology": ["technology", "technological advancements", "innovation"],
"has": ["has", "possesses", "holds"],
"transformed": ["transformed", "changed", "altered"],
"traditional": ["traditional", "conventional", "standard"],
"classrooms": ["classrooms", "schools", "educational settings"],
"into": ["into", "transformed into", "changed into"],
"dynamic": ["dynamic", "energetic", "vibrant"],
"learning": ["learning", "education", "instruction"],
"environments": ["environments", "settings", "conditions"],
"where": ["where", "in which", "wherein"],
"students": ["students", "pupils", "learners"],
"can": ["can", "could", "may"],
"access": ["access", "entry", "admission"],
"a": ["a", "an", "one"],
"wealth": ["wealth", "abundance", "riches"],
"of": ["of", "in", "within"],
"educational": ["educational", "instructional", "academic"],
"resources": ["resources", "materials", "tools"],
"online": ["online", "on the internet", "over the web"],
"participate": ["participate", "engage", "take part"],
"in": ["in", "within", "during"],
"interactive": ["interactive", "participatory", "engaging"],
"lessons": ["lessons", "classes", "sessions"],
"and": ["and", "as well as", "along with"],
"collaborate": ["collaborate", "cooperate", "work together"],
"with": ["with", "using", "by means of"],
"peers": ["peers", "colleagues", "fellow students"],
"globally": ["globally", "worldwide", "internationally"],
"Digital": ["Digital", "Electronic", "Computerized"],
"textbooks": ["textbooks", "e-books", "digital books"],
"e-learning": ["e-learning", "online learning", "digital learning"],
"platforms": ["platforms", "sites", "systems"],
"and": ["and", "as well as", "along with"],
"virtual": ["virtual", "simulated", "computer-generated"],
"reality": ["reality", "real-world", "actuality"],
"simulations": ["simulations", "models", "representations"],
"offer": ["offer", "provide", "present"],
"engaging": ["engaging", "captivating", "interesting"],
"alternatives": ["alternatives", "options", "choices"],
"to": ["to", "towards", "into"],
"traditional": ["traditional", "conventional", "standard"],
"teaching": ["teaching", "instruction", "education"],
"methods": ["methods", "approaches", "techniques"],
"catering": ["catering", "serving", "providing"],
"to": ["to", "towards", "into"],
"diverse": ["diverse", "varied", "different"],
"learning": ["learning", "education", "instruction"],
"styles": ["styles", "approaches", "methods"],
"and": ["and", "as well as", "along with"],
"preferences": ["preferences", "choices", "selections"],
"The": ["The", "That", "This"],
"entertainment": ["entertainment", "amusement", "diversion"],
"industry": ["industry", "business", "sector"],
"has": ["has", "possesses", "holds"],
"also": ["also", "additionally", "furthermore"],
"undergone": ["undergone", "experienced", "gone through"],
"a": ["a", "an", "one"],
"digital": ["digital", "electronic", "computerized"],
"revolution": ["revolution", "transformation", "change"],
"with": ["with", "using", "by means of"],
"streaming": ["streaming", "broadcasting", "transmission"],
"services": ["services", "facilities", "amenities"],
"online": ["online", "internet", "web-based"],
"The": ["The", "That", "This"],
  "rapid": ["quick", "swift", "fast"],
  "advancement": ["progress", "development", "improvement"],
  "of": ["of", "involving", "pertaining to"],
  "technology": ["technology", "technological advancements", "innovation"],
  "in": ["in", "within", "inside"],
  "the": ["the", "this", "that"],
  "modern": ["contemporary", "current", "up-to-date"],
  "era": ["age", "epoch", "period"],
  "has": ["has", "possesses", "holds"],
  "revolutionized": ["transformed", "changed", "altered"],
  "nearly": ["almost", "virtually", "practically"],
  "every": ["every", "each", "all"],
  "aspect": ["facet", "element", "dimension"],
  "human": ["human", "mankind's", "people's"],
  "life": ["life", "existence", "living"],
  "From": ["From", "Starting from", "Beginning with"],
  "communication": ["communication", "interaction", "connection"],
  "and": ["and", "as well as", "along with"],
  "transportation": ["transportation", "transit", "travel"],
  "to": ["to", "towards", "into"],
  "healthcare": ["healthcare", "medical care", "medical treatment"],
  "entertainment": ["entertainment", "amusement", "diversion"],
  "plays": ["plays", "acts", "performs"],
  "a": ["a", "an", "one"],
  "pivotal": ["crucial", "essential", "critical"],
  "role": ["role", "function", "responsibility"],
  "shaping": ["shaping", "molding", "forming"],
  "our": ["our", "the", "the"],
  "daily": ["daily", "everyday", "day-to-day"],
  "experiences": ["experiences", "encounters", "events"],
  "The": ["The", "That", "This"],
  "advent": ["arrival", "coming", "appearance"],
  "of": ["of", "in", "on"],
  "the": ["the", "the", "the"],
  "internet": ["internet", "web", "online"],
  "smartphones": ["smartphones", "mobile phones", "cellphones"],
  "and": ["and", "as well as", "along with"],
  "social": ["social", "societal", "community"],
  "media": ["media", "communications", "networks"],
  "platforms": ["platforms", "sites", "systems"],
  "has": ["has", "possesses", "holds"],
  "interconnected": ["connected", "linked", "joined"],
  "people": ["people", "individuals", "persons"],
  "across": ["across", "throughout", "over"],
  "the": ["the", "the", "the"],
  "globe": ["globe", "world", "planet"],
  "facilitating": ["facilitating", "aiding", "assisting"],
  "instant": ["instant", "immediate", "quick"],
  "communication": ["communication", "interaction", "connection"],
  "and": ["and", "as well as", "along with"],
  "information": ["information", "data", "facts"],
  "sharing": ["sharing", "exchange", "transmission"],
  "Tasks": ["Tasks", "Assignments", "Jobs"],
  "that": ["that", "which", "those"],
  "once": ["once", "previously", "formerly"],
  "required": ["required", "needed", "demanded"],
  "extensive": ["extensive", "comprehensive", "thorough"],
  "manual": ["manual", "physical", "hand"],
  "labor": ["labor", "work", "effort"],
  "or": ["or", "or else", "otherwise"],
  "time-consuming": ["time-consuming", "laborious", "tedious"],
  "processes": ["processes", "procedures", "methods"],
  "can": ["can", "could", "may"],
  "now": ["now", "at present", "currently"],
  "be": ["be", "become", "turn into"],
  "accomplished": ["accomplished", "achieved", "completed"],
  "with": ["with", "using", "by means of"],
  "the": ["the", "the", "the"],
  "click": ["click", "press", "tap"],
  "of": ["of", "by", "through"],
  "a": ["a", "an", "one"],
  "button": ["button", "switch", "control"],
  "or": ["or", "or else", "otherwise"],
  "the": ["the", "the", "the"],
  "swipe": ["swipe", "slide", "brush"],
  "of": ["of", "by", "through"],
  "a": ["a", "an", "one"],
  "screen": ["screen", "display", "monitor"],
  "In": ["In", "Within", "Inside"],
  "the": ["the", "the", "the"],
  "field": ["field", "domain", "area"],
  "of": ["of", "in", "within"],
  "healthcare": ["healthcare", "medical care", "medical treatment"],
  "technological": ["technological", "technical", "scientific"],
  "innovations": ["innovations", "developments", "advancements"],
  "have": ["have", "possess", "hold"],
  "led": ["led", "guided", "directed"],
  "to": ["to", "towards", "into"],
  "breakthroughs": ["breakthroughs", "advances", "discoveries"],
  "in": ["in", "within", "inside"],
  "medical": ["medical", "medicinal", "health"],
  "treatments": ["treatments", "therapies", "remedies"],
  "diagnostics": ["diagnostics", "analysis", "examination"],
  "and": ["and", "as well as", "along with"],
  "patient": ["patient", "client", "customer"],
  "care": ["care", "concern", "attention"],
  "Telemedicine": ["Telemedicine", "Telehealth", "Remote medicine"],
  "allows": ["allows", "permits", "enables"],
  "patients": ["patients", "clients", "individuals"],
  "to": ["to", "towards", "into"],
  "consult": ["consult", "seek advice", "talk"],
  "with": ["with", "using", "by means of"],
  "healthcare": ["healthcare", "medical", "health"]
};

// Function to paraphrase the input text
function paraphraseText(inputText) {
    const words = inputText.split(' ');

    const paraphrasedWords = words.map(word => {
        const cleanWord = word.toLowerCase().replace(/[^\w\s]/gi, '');
        if (synonyms[cleanWord]) {
            const synonymList = [cleanWord, ...synonyms[cleanWord]];
            const randomIndex = Math.floor(Math.random() * synonymList.length);
            return word.replace(cleanWord, synonymList[randomIndex]);
        } else {
            return word;
        }
    });

    return paraphrasedWords.join(' ');
}
app.post('/paraphrase', (req, res) => {
    const inputText = req.body.inputText;

    // Check if inputText is provided
    if (!inputText) {
        return res.status(400).json({ error: 'Input text is required' });
    }

    // Paraphrase the input text
    const paraphrasedText = paraphraseText(inputText);

    // Send the paraphrased text in the response
    res.json({ paraphrasedText });
});
app.get('/paraphrase', (req, res) => {
    res.json({ synonyms });
    if (!inputText) {
        return res.status(400).json({ error: 'Input text is required' });
    }
});

app.listen(port, () => {
    console.log(`Server is running on port ${port}`);
});
